const monthName='سبتمبر 2026';
const totals={sales:15160835,returns:911919,collections:11663678,netSales:14248916,operatingDebt:2585238};
const data={
 reps:[['مومن على',6952090,167495,4844705],['حمزه ياسين',3624310,429489,3306568],['يوسف حمدى',1579185,162940,968655],['سيف الدين احمد',1495435,27200,1436945],['إبراهيم حمدى',1009345,79275,604995],['عبد الرحمن على',500470,45520,501810]],
 sales:[['3110','moaamen Mario mansora','سيف الدين احمد',39625,'30 سبتمبر'],['3108','yousef crown ibrahemia','يوسف حمدى',8400,'30 سبتمبر'],['3107','yousef crown ibrahemia','يوسف حمدى',10400,'30 سبتمبر'],['3106','ibrahim el dakhakhny atlas','إبراهيم حمدى',2160,'30 سبتمبر'],['3105','Hamza vape store','حمزه ياسين',37800,'30 سبتمبر'],['3104','sief yasser admez','سيف الدين احمد',14250,'30 سبتمبر'],['3103','Hamza vape store','حمزه ياسين',30800,'29 سبتمبر'],['3102','Hamza Wabor Elmaya','حمزه ياسين',21600,'29 سبتمبر']],
 collections:[['yousef mohamed eldakhakhny sidi gaber','يوسف حمدى',9300,'30 سبتمبر'],['yousef khalifa 2','يوسف حمدى',3000,'30 سبتمبر'],['yousef micky smoha','يوسف حمدى',8000,'30 سبتمبر'],['yousef she7ata gom3a','يوسف حمدى',5000,'30 سبتمبر'],['yousef eldakhakhny smoha moderya','يوسف حمدى',5000,'30 سبتمبر'],['yousef eldakhakhny smoha elbaraka','يوسف حمدى',6500,'30 سبتمبر'],['yousef mohamed elawamy','يوسف حمدى',20000,'30 سبتمبر'],['yousef candy bird','يوسف حمدى',10200,'30 سبتمبر']],
 returns:[['439','sief basam alkhdash','سيف الدين احمد',2100,'30 سبتمبر'],['438','abd elrahman mahmoud sayed','عبد الرحمن على',17800,'30 سبتمبر'],['437','sief abd allah','عبد الرحمن على',6500,'30 سبتمبر'],['436','mina kajo','يوسف حمدى',20100,'30 سبتمبر'],['435','yousef eldakhakhny smoha elbaraka','يوسف حمدى',650,'30 سبتمبر'],['434','yousef eldakhakhny smoha moderya','يوسف حمدى',600,'30 سبتمبر'],['433','ibrahim zuse 45','إبراهيم حمدى',500,'30 سبتمبر'],['429','yousef eldakhakhny smoha moderya','يوسف حمدى',1800,'27 سبتمبر']],
 debts:[['Eltahra vape store','مومن على',660000],['ahmed hassan','مومن على',645875],['mostafa nagiub','مومن على',386500],['Mina Elklan','حمزه ياسين',305557],['Hamza vape store','حمزه ياسين',291966],['yousef kero samy','يوسف حمدى',139475],['omar elawamy','مومن على',128000],['mostafa nagiub','حمزه ياسين',100250],['ahmed arese port','مومن على',92000],['Besenty Sharm','مومن على',87250],['Hamza Wabor Elmaya','حمزه ياسين',75970],['Labib Store','مومن على',68625],['yousef mohamed elawamy','يوسف حمدى',56000],['ibrahim zuse 45','إبراهيم حمدى',55870],['zaghlol','مومن على',50325]]
};
const pages={home:'نظرة عامة',sales:'المبيعات',collections:'التحصيلات',returns:'المرتجعات',debts:'مديونيات العملاء'};
const content=document.querySelector('#pageContent');
const money=v=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(v)+' ج.م';
function table(headers,rows){return `<div class="card table-card"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function salesRows(rows){return rows.map(r=>[`#${r[0]}`,r[1],r[2],money(r[3]),r[4]])}
function render(page='home'){
 document.querySelector('#pageTitle').textContent=pages[page];
 if(page==='home'){content.innerHTML=`<section class="hero-dashboard"><div><span class="hero-kicker">MOU DISTRO • سبتمبر 2026</span><h1>أهلًا، إدارة MOU <em>✦</em></h1><p>هذه صورة أداء التوزيع اليوم. تابع البيع والتحصيل والرصيد من مكان واحد.</p></div><button class="hero-action" data-go="sales">عرض الفواتير <span>←</span></button></section><section class="stats stats-new"><div class="card accent"><span class="metric-icon aqua-icon">↗</span><p>إجمالي المبيعات</p><h3>${money(totals.sales)}</h3><small>صافي المبيعات ${money(totals.netSales)}</small></div><div class="card purple"><span class="metric-icon violet-icon">◉</span><p>إجمالي التحصيلات</p><h3>${money(totals.collections)}</h3><small>نسبة التحصيل 81.9%</small></div><div class="card orange"><span class="metric-icon orange-icon">↩</span><p>إجمالي المرتجعات</p><h3>${money(totals.returns)}</h3><small>6.0% من المبيعات</small></div><div class="card red"><span class="metric-icon red-icon">₪</span><p>مديونية الفترة</p><h3>${money(totals.operatingDebt)}</h3><small>تحتاج متابعة</small></div></section><section class="insight-grid"><div class="card trend-card"><div class="section-heading"><div><span>ملخص النشاط</span><h3>المبيعات والتحصيلات</h3></div><b>سبتمبر</b></div><div class="bars" aria-label="رسم توضيحي للمبيعات والتحصيلات"><div><i style="height:44%"></i><i style="height:36%"></i><small>الأسبوع 1</small></div><div><i style="height:63%"></i><i style="height:52%"></i><small>الأسبوع 2</small></div><div><i style="height:82%"></i><i style="height:70%"></i><small>الأسبوع 3</small></div><div><i style="height:96%"></i><i style="height:81%"></i><small>الأسبوع 4</small></div></div><div class="chart-key"><span><i></i> المبيعات</span><span><i></i> التحصيلات</span></div></div><aside class="card focus-card"><span>تنبيه المتابعة</span><h3>المديونيات التشغيلية</h3><strong>${money(totals.operatingDebt)}</strong><p>أكبر رصيد حاليًا لدى <b>Eltahra vape store</b> بقيمة ${money(660000)}.</p><button data-go="debts">مراجعة المديونيات ←</button></aside></section><section class="bottom-grid"><div class="card team-card"><div class="section-heading"><div><span>ترتيب الأداء</span><h3>أفضل المناديب</h3></div><button data-go="sales">تفاصيل</button></div>${data.reps.slice(0,4).map((r,i)=>`<div class="rep-row"><span class="rank">0${i+1}</span><div class="rep-name"><b>${r[0]}</b><small>${money(r[1])} مبيعات</small></div><div class="rep-progress"><i style="width:${Math.round(r[1]/data.reps[0][1]*100)}%"></i></div><strong>${Math.round(r[1]/data.reps[0][1]*100)}%</strong></div>`).join('')}</div><div class="card activity-card"><div class="section-heading"><div><span>آخر العمليات</span><h3>حركة الفواتير</h3></div><button data-go="sales">الكل</button></div>${data.sales.slice(0,4).map(r=>`<div class="activity-row"><span class="activity-mark">#</span><div><b>${r[1]}</b><small>فاتورة ${r[0]} • ${r[2]}</small></div><strong>${money(r[3])}</strong></div>`).join('')}</div></section>`}
 else if(page==='sales')content.innerHTML=`<div class="page-head"><div><h3>المبيعات</h3><p class="subtext">آخر الفواتير المسجلة في ${monthName}</p></div><button class="primary">+ إضافة فاتورة</button></div>${table(['رقم الفاتورة','العميل','المندوب','القيمة','التاريخ'],salesRows(data.sales))}`;
 else if(page==='collections')content.innerHTML=`<div class="page-head"><div><h3>التحصيلات</h3><p class="subtext">آخر التحصيلات المسجلة في ${monthName}</p></div><button class="primary">+ تسجيل تحصيل</button></div>${table(['العميل','المندوب','القيمة','التاريخ'],data.collections.map(r=>[r[0],r[1],money(r[2]),r[3]]))}`;
 else if(page==='returns')content.innerHTML=`<div class="page-head"><div><h3>المرتجعات</h3><p class="subtext">آخر المرتجعات المسجلة في ${monthName}</p></div><button class="primary">+ تسجيل مرتجع</button></div>${table(['رقم المرتجع','العميل','المندوب','القيمة','التاريخ'],salesRows(data.returns))}`;
 else content.innerHTML=`<div class="page-head"><div><h3>مديونيات العملاء</h3><p class="subtext">الرصيد التشغيلي لشهر سبتمبر: مبيعات − مرتجعات − تحصيلات</p></div><button class="primary">تصدير كشف</button></div>${table(['العميل','المندوب','المديونية التشغيلية'],data.debts.map(r=>[r[0],r[1],`<span class="tag warn">${money(r[2])}</span>`]))}`;
 document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>selectPage(x.dataset.go));
}
function selectPage(page){document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));render(page)}
document.querySelectorAll('.nav-link').forEach(x=>x.onclick=()=>selectPage(x.dataset.page));
document.querySelector('#today').textContent='بيانات التقرير: '+monthName;
const loginView=document.querySelector('#loginView'),appView=document.querySelector('#appView');
const usernameInput=document.querySelector('#username'),passwordInput=document.querySelector('#password'),loginError=document.querySelector('#loginError'),userName=document.querySelector('#userName');
document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const u=usernameInput.value.trim(),p=passwordInput.value.trim();loginError.hidden=!!(u&&p);if(u&&p){userName.textContent=u;loginView.hidden=true;appView.hidden=false;render()}};
document.querySelector('#logout').onclick=()=>{appView.hidden=true;loginView.hidden=false;passwordInput.value=''};
if(new URLSearchParams(location.search).has('preview')){userName.textContent='إدارة MOU Distro';loginView.hidden=true;appView.hidden=false;render()}
